[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["better-sqlite3"]
  included_files = ["data/erebus.sqlite"]

[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/api/v1/:splat"
  status = 200
