export const TYPES = {
  ICoreAdapter: Symbol.for('ICoreAdapter'),
  DiceService: Symbol.for('DiceService'),
  DiceController: Symbol.for('DiceController'),
  DrizzleDb: Symbol.for('DrizzleDb'),
  ISkillRepository: Symbol.for('ISkillRepository'),
  ISkillService: Symbol.for('ISkillService'),
  SkillController: Symbol.for('SkillController'),
  IWeaponRepository: Symbol.for('IWeaponRepository'),
  IWeaponService: Symbol.for('IWeaponService'),
  WeaponController: Symbol.for('WeaponController'),
  IEnhancementRepository: Symbol.for('IEnhancementRepository'),
  IEnhancementService: Symbol.for('IEnhancementService'),
  EnhancementController: Symbol.for('EnhancementController'),
  LogsService: Symbol.for('LogsService'),
  LogsController: Symbol.for('LogsController'),
  ICombatSkillRepository: Symbol.for('ICombatSkillRepository'),
  ICombatSkillService: Symbol.for('ICombatSkillService'),
  CombatSkillController: Symbol.for('CombatSkillController'),
};
